title: Coding the Direction: Mapping My Data Science Journey
description: Step into the world where data science, programming, and creativity collide. This is my coding portfolio, where curiosity and problem-solving drive me to innovate. From geospatial analysis to sleek algorithms, I’m constantly pushing boundaries and refining my craft. Join me as I transform data into insights and code into real-world solutions—one project at a time.
url: https://mjbroqueza.github.io
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

author:
  name: Mark James Broqueza
  email: markbroqueza23@gmail.com

social:
  github: mjbroqueza
  linkedin: markjames-broqueza
